language: cpp
compiler:
- gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6

script:
  - mkdir build
  - cd build/
  - cmake ..
  - make
  - ./main_exe